In [1]:
import pandas as pd


In [2]:
df = pd.read_csv('./austen_listings.csv')

C:\Users\PhatDeluxe\Anaconda3\envs\tensor_flow\lib\site-packages\IPython\core\interactiveshell.py:3051: DtypeWarning: Columns (43,61,62) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
pd.set_option('max_columns', None)
df.head()

id                        listing_url       scrape_id last_scraped  \
0  2265  https://www.airbnb.com/rooms/2265  20191112224534   2019-11-13   
1  5245  https://www.airbnb.com/rooms/5245  20191112224534   2019-11-13   
2  5456  https://www.airbnb.com/rooms/5456  20191112224534   2019-11-13   
3  5769  https://www.airbnb.com/rooms/5769  20191112224534   2019-11-13   
4  6413  https://www.airbnb.com/rooms/6413  20191112224534   2019-11-13   

                                                name  \
0   Zen-East in the Heart of Austin (monthly rental)   
1  Eco friendly, Colorful, Clean, Cozy monthly share   
2          Walk to 6th, Rainey St and Convention Ctr   
3                                     NW Austin Room   
4                      Gem of a Studio near Downtown   

                                             summary  \
0  Zen East is situated in a vibrant & diverse mu...   
1  Situated in a vibrant & diverse multicultural ...   
2  Great central  location for walking to Convent...   
3                                                NaN   
4  Great studio apartment, perfect for couples or...   

                                               space  \
0  This colorful and clean 1923 house was complet...   
1  This green, colorful, clean and cozy house was...   
2  Cute Private Studio apartment located in Willo...   
3  Looking for a comfortable inexpensive room to ...   
4  (License #114332) Large, contemporary studio a...   

                                         description experiences_offered  \
0  Zen East is situated in a vibrant & diverse mu...                none   
1  Situated in a vibrant & diverse multicultural ...                none   
2  Great central  location for walking to Convent...                none   
3  Looking for a comfortable inexpensive room to ...                none   
4  Great studio apartment, perfect for couples or...                none   

                               neighborhood_overview  \
0                                                NaN   
1                                                NaN   
2  My neighborhood is ideally located if you want...   
3  Quiet neighborhood with lots of trees and good...   
4  Travis Heights is one of the oldest neighborho...   

                                               notes  \
0  A 2013 Genuine Buddy Scooter 125 may be availa...   
1  Please note: A two story studio was built in t...   
2  Parking on street requires a permit.  Permits ...   
3                                                NaN   
4  Our calendar only extends a few months. If you...   

                                             transit  \
0  5 min walk to Capitol Metro Rail (train that t...   
1                                                NaN   
2  Bus stop around the block.  Uber, Lyft, Ride, ...   
3  We are approximately 16 miles from downtown Au...   
4  Parking for our place is on the street, roughl...   

                                              access  \
0  Several local restaurants, small clubs, music ...   
1                                                NaN   
2                       Guests have access to patio.   
3                             Gravel Parking Kitchen   
4     Private patio with lounge chairs and umbrella.   

                                         interaction  \
0  Depending on your dates and arrival time, I am...   
1  I should be available, upon your arrival, to a...   
2  I am happy to welcome my guests and show them in.   
3  We interact with our guests as little or as mu...   
4  You may see us during your stay, but you'll ma...   

                                         house_rules  thumbnail_url  \
0  • Check-in time is 4 pm. Check out is 11 am. I...            NaN   
1  A brief profile for all guests along with phot...            NaN   
2  No Pets allowed.  No smoking in the room. No m...            NaN   
3  I will need to see identification at check in....            NaN   
4  Posted prices include the 9% in local occup

In [4]:
df['zipcode'].value_counts()

78704       1710
78702       1114
78741        480
78701        470
78704.0      457
            ... 
78767          1
78669          1
78712          1
78739.0        1
TX 78702       1
Name: zipcode, Length: 99, dtype: int64

In [7]:
df['price'].value_counts()

$150.00      381
$100.00      360
$200.00      318
$250.00      262
$125.00      255
            ... 
$3,018.00      1
$503.00        1
$3,561.00      1
$374.00        1
$331.00        1
Name: price, Length: 682, dtype: int64

In [8]:
features = ['bedrooms', 'bathrooms', 'zipcode']
target = 'price'

In [9]:
df_copy = pd.DataFrame()

In [10]:
df[features] = df[features].fillna(method='ffill')

In [44]:
def price_to_float(price):
    price = price.replace('$', '')
    price = price.replace(',', '')
    float(price)
    return price

df_copy['price'] = df['price'].apply(price_to_float)
df_copy['price'] = pd.to_numeric(df_copy['price'])

In [12]:
df_copy.head()

price
0  225.00
1  100.00
2   95.00
3   40.00
4   99.00

In [13]:
def zipcode_to_int(zipcode):
    zipcode = str(zipcode)
    zipcode = zipcode.replace('TX', '')
    zipcode = zipcode.replace(' ', '')
    zipcode = zipcode.replace('.0', '')
    zipcode = int(zipcode)
    return zipcode

df_copy['zipcode'] = df['zipcode'].apply(zipcode_to_int)

In [14]:
df['zipcode'] = df_copy['zipcode']

In [15]:
len(df.columns)

106

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [17]:
df[features].isnull().sum()

bedrooms     0
bathrooms    0
zipcode      0
dtype: int64

In [25]:
model = Sequential()

model.add(Dense(3, input_dim=3, activation='relu', name='dense_0'))
model.add(Dense(3, activation='relu', name='dense_1'))
model.add(Dense(2, activation='relu', name='dense_2'))
model.add(Dense(2, activation='relu', name='dense_3'))
model.add(Dense(1, name='dense_4'))

model.compile(loss='MSE', optimizer='adam', metrics=['mean_squared_error'])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_0 (Dense)              (None, 3)                 12        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 12        
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 8         
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 3         
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.fit(df[features], df_copy['price'], epochs=10000, verbose=0, validation_split=1)

In [28]:
import numpy as np
test_2 = np.array([[2.0, 2.0, 78702]])

model.predict(test_2)

array([[428.76666]], dtype=float32)

In [30]:
pred = model.predict(test_2)

In [32]:
np.around(pred)

array([[429.]], dtype=float32)

In [83]:
model.save_weights('baseline_model.h5')

In [33]:
model.save('baseline_model.h5')

In [18]:
from tensorflow.keras.models import load_model

model = load_model('baseline_model.h5')

In [40]:
pd.set_option('max_rows', None)

df_copy.dtypes

price      object
zipcode     int64
dtype: object

In [30]:
import numpy as np
test = np.array([[7, 7.0, 78731]])

model.predict(test)

array([[428.76666]], dtype=float32)